# Generated by Django 4.2.5 on 2023-09-18 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_jobs_options_alter_skills_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='field_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(code=400, message='Mobile is not in correct format', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prior_highest_education',
            field=models.IntegerField(choices=[(1, 'Less than GED'), (2, 'GED'), (3, 'Some college'), (4, 'Associate`s'), (5, 'Bachelor`s'), (6, 'Master`s'), (7, 'Doctoral')], null=True),
        ),
    ]
