# Generated by Django 4.2.5 on 2023-09-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userprofile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='field_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='criminal_conviction',
            field=models.IntegerField(blank=True, choices=[(1, 'misdemeanor'), (2, 'felony')], null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.IntegerField(choices=[(1, 'Some college'), (2, 'Associate`s'), (3, 'Bachelor`s'), (4, 'Master`s'), (5, 'Doctoral')]),
        ),
    ]
